name: Testnet check

on: 
  push:
    branches:
      - testnet-check
      - test
  pull_request:
    branches:
      - testnet-check

jobs:
  run-testnet-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout chain source code
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Docker compose
        run: |
          docker-compose up -d
          docker container rename baby_node_1 baby-node-1
      - name: check chain id
        run: |
          chmod a+x ./homework/check-chain-id.sh
          ./homework/check-chain-id.sh