name: Testnet check

on: 
  push:
    branches:
      - testnet-check
      - test
  pull_request:
    branches:
      - testnet-check

jobs:
  run-testnet-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout chain source code
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Docker compose
        run: |
          docker-compose up -d
          docker container rename baby_node_1 baby-node-1
          docker exec baby-node-1 babyd version
      # - name: Setup tunnel
      #   uses: joshlarsen/ssh-tunnel-action@v1.2
      #   with:
      #     timeout: 1h
      #     ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      #     ngrok_token: ${{ secrets.NGROK_TOKEN }}
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: check chain id
        run: |
          id
          chmod a+x ./homework/check-chain-id.sh
          bash homework/check-chain-id.sh
      